# Generated by Django 5.1.6 on 2025-03-04 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0006_alter_customer_id_alter_feedback_id_alter_orders_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='size',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='size',
            field=models.CharField(choices=[('S', 'Small'), ('M', 'Medium'), ('XL', 'Extra Large')], default='M', max_length=2),
        ),
    ]
